version: '3.8'

services:
  tale:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: ["uvicorn", "source.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
