from content import Content

class PostProcessor:
    """
    The class which processes the content generated by the Summarizer class.
    Attributes:
        content (Content) : The content to be processed
    """
    content = Content('', [''], [''])

    def __init__(self, content):
        """
        The constructor for the PostProcessor class.
        Attributes:
            content (Content) : The content to be processed
        """
        self.content = content
        return


    def generateHtml(self):
        """
        Generates a html string from the content.
        Returns:
            html (str) : The html string
        """
        html = '<!DOCTYPE html>\n<html>\n<head>\n<title>' + self.content.title + '</title>\n</head>\n<body>\n'
        for text in self.content.text:
            html += '<p>' + text + '</p>\n'
        for image in self.content.images:
            html += '<img src="' + image + '">\n'
        html += '</body>\n</html>'
        return html
    
    def writeHtml(self, path, html):
        """
        Writes the html string to a file.
        Attributes:
            path (str) : The path to the html file
            html (str) : The html string to be written
        """
        file = open(path, 'w')
        file.write(html)
        file.close()
        return
    
    def process(self):
        """
        Processes the content by generating a html and writing it into a file.
        """
        html = self.generateHtml()
        self.writeHtml('output.html', html)
        return
